import type { AcceptanceCriterion, AcceptancePack } from "./types.js";

function slugify(label: string): string {
	return label
		.trim()
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "-")
		.replace(/^-+|-+$/g, "")
		.slice(0, 48);
}

function buildCriterion(
	label: string,
	description: string,
	kind: AcceptanceCriterion["kind"],
	source: AcceptanceCriterion["source"],
	evaluationMode: AcceptanceCriterion["evaluationMode"] = "manual",
	required = true,
): AcceptanceCriterion {
	return {
		id: slugify(label) || `criterion-${Math.random().toString(36).slice(2, 8)}`,
		label,
		description,
		kind,
		source,
		required,
		evaluationMode,
		sourceReason:
			source === "input"
				? "Explicit request input."
				: source === "heuristic"
					? "Derived from prompt heuristics."
					: "Generated by the default repository acceptance policy.",
	};
}

function mapRequirementList(
	items: string[] | undefined,
	kind: AcceptanceCriterion["kind"],
	evaluationMode: AcceptanceCriterion["evaluationMode"] = "manual",
): AcceptanceCriterion[] {
	return (items || []).map((item, index) =>
		buildCriterion(`${kind}-${index + 1}`, item, kind, "input", evaluationMode, true),
	);
}

export function buildAcceptancePack(input: {
	prompt: string;
	acceptanceCriteria?: string[];
	responsiveRequirements?: string[];
	a11yRequirements?: string[];
	visualRequirements?: string[];
	manualReviewItems?: string[];
}): AcceptancePack {
	const criteria: AcceptanceCriterion[] = [
		buildCriterion(
			"quality-gate-must-pass",
			"The generated change must pass the generic quality gate.",
			"quality_gate",
			"generated",
			"automatic",
		),
	];

	if (input.acceptanceCriteria?.length) {
		criteria.push(
			...mapRequirementList(input.acceptanceCriteria, "manual_review", "manual"),
		);
	} else {
		criteria.push(
			buildCriterion(
				"prompt-intent-review",
				"Reviewer must confirm the generated UI still matches the prompt intent.",
				"manual_review",
				"heuristic",
				"manual",
			),
		);
	}

	if (
		input.responsiveRequirements?.length ||
		/\b(mobile|desktop|tablet|responsive|breakpoint)\b/i.test(input.prompt)
	) {
		criteria.push(
			...(
				input.responsiveRequirements?.length
					? mapRequirementList(input.responsiveRequirements, "responsive", "manual")
					: [
							buildCriterion(
								"responsive-review",
								"Reviewer must confirm the UI behaves acceptably across the intended breakpoints.",
								"responsive",
								"heuristic",
								"manual",
							),
						]
			),
		);
	}

	if (
		input.a11yRequirements?.length ||
		/\b(a11y|accessibility|keyboard|focus|aria)\b/i.test(input.prompt)
	) {
		criteria.push(
			...(
				input.a11yRequirements?.length
					? mapRequirementList(input.a11yRequirements, "a11y", "manual")
					: [
							buildCriterion(
								"a11y-review",
								"Reviewer must confirm the experience satisfies the prompt's accessibility intent.",
								"a11y",
								"heuristic",
								"manual",
							),
						]
			),
		);
	}

	if (
		input.visualRequirements?.length ||
		/\b(hero|landing|polished|visual|brand|design)\b/i.test(input.prompt)
	) {
		criteria.push(
			...(
				input.visualRequirements?.length
					? mapRequirementList(input.visualRequirements, "visual", "manual")
					: [
							buildCriterion(
								"visual-review",
								"Reviewer must confirm the visuals meet the intended design quality.",
								"visual",
								"heuristic",
								"manual",
							),
						]
			),
		);
	}

	if (input.manualReviewItems?.length) {
		criteria.push(
			...mapRequirementList(input.manualReviewItems, "manual_review", "manual"),
		);
	}

	return {
		version: 1,
		prompt: input.prompt,
		criteria,
		unresolvedAssumptions: [],
		recommendedChecks: ["quality_gate", "manual_review"],
	};
}
